-- 002 Seed: fragrance_templates — 10 classical perfumes as Neo4j degradation fallback
-- Run after 001-mvp-schema.sql. Idempotent (ON CONFLICT DO NOTHING on name).

INSERT INTO fragrance_templates (name, notes_top, notes_middle, notes_base, mood_tags, scene_tags, story_copy) VALUES
('No.5 Chanel',
 ARRAY['醛香 Aldehydes','依兰 Ylang-Ylang','橙花 Neroli'],
 ARRAY['玫瑰 Rose','茉莉 Jasmine','鸢尾 Iris'],
 ARRAY['檀木 Sandalwood','香草 Vanilla','岩兰草 Vetiver'],
 ARRAY['romance','calm','nostalgia'],
 ARRAY['date','gift'],
 'A timeless icon. Aldehydic sparkle opens to a heart of rose and jasmine, grounded by sandalwood and vanilla. The scent of confidence.'),
('J''adore Dior',
 ARRAY['柑橘 Citrus','香柠檬 Bergamot','蜜瓜 Melon'],
 ARRAY['玫瑰 Rose','茉莉 Jasmine','铃兰 Lily-of-the-Valley'],
 ARRAY['麝香 Musk','黑莓 Blackberry','雪松 Cedar'],
 ARRAY['joy','romance','excitement'],
 ARRAY['date','party'],
 'A radiant bouquet. Juicy melon and bergamot dance with jasmine and rose, wrapped in soft musk. Modern femininity bottled.'),
('Light Blue Dolce & Gabbana',
 ARRAY['柠檬 Lemon','青苹果 Green Apple','风信子 Bellflower'],
 ARRAY['茉莉 Jasmine','竹子 Bamboo','白玫瑰 White Rose'],
 ARRAY['雪松 Cedar','琥珀 Amber','麝香 Musk'],
 ARRAY['joy','calm','excitement'],
 ARRAY['work','explore'],
 'A Mediterranean breeze. Crisp lemon and green apple meet airy jasmine and warm cedar. Effortless and sun-kissed.'),
('L''Eau d''Issey Issey Miyake',
 ARRAY['莲花 Lotus','小苍兰 Freesia','仙客来 Cyclamen'],
 ARRAY['百合 Lily','牡丹 Peony','康乃馨 Carnation'],
 ARRAY['麝香 Musk','琥珀 Amber','雪松 Cedar'],
 ARRAY['calm','nostalgia','romance'],
 ARRAY['home','gift'],
 'Water and flowers in harmony. Lotus rises from still water, touched by lily and soft musk. Pure, transparent, poetic.'),
('Shalimar Guerlain',
 ARRAY['佛手柑 Bergamot','柑橘 Citrus','柠檬 Lemon'],
 ARRAY['玫瑰 Rose','茉莉 Jasmine','鸢尾 Iris'],
 ARRAY['香草 Vanilla','零陵香豆 Tonka Bean','檀木 Sandalwood'],
 ARRAY['romance','nostalgia','melancholy'],
 ARRAY['date','gift'],
 'The original oriental. Bergamot brightens a heart of rose, then vanilla and tonka weave a warm, sensual trail. A legend since 1925.'),
('Black Orchid Tom Ford',
 ARRAY['黑加仑 Blackcurrant','依兰 Ylang-Ylang','佛手柑 Bergamot'],
 ARRAY['黑兰花 Black Orchid','莲花 Lotus','茉莉 Jasmine'],
 ARRAY['广藿香 Patchouli','琥珀 Amber','檀木 Sandalwood'],
 ARRAY['romance','melancholy','excitement'],
 ARRAY['party','date'],
 'Dark and magnetic. Black truffle and black orchid create an intoxicating bloom, deepened by patchouli and amber. Unforgettable.'),
('L''Homme Yves Saint Laurent',
 ARRAY['生姜 Ginger','佛手柑 Bergamot','柠檬 Lemon'],
 ARRAY['紫罗兰 Violet','罗勒 Basil','白胡椒 White Pepper'],
 ARRAY['雪松 Cedar','零陵香豆 Tonka Bean','麝香 Musk'],
 ARRAY['calm','excitement','joy'],
 ARRAY['work','explore'],
 'Modern elegance. Ginger and bergamot open with energy, violet and basil add sophistication, cedar anchors with quiet strength.'),
('Acqua di Giò Giorgio Armani',
 ARRAY['柑橘 Citrus','佛手柑 Bergamot','青柠 Lime'],
 ARRAY['茉莉 Jasmine','迷迭香 Rosemary','牡丹 Peony'],
 ARRAY['广藿香 Patchouli','雪松 Cedar','橡苔 Oakmoss'],
 ARRAY['joy','calm','excitement'],
 ARRAY['work','explore'],
 'The ocean breeze. Citrus and lime crash like waves, rosemary and jasmine float on salt air, patchouli grounds like sea-worn rock.'),
('La Vie Est Belle Lancôme',
 ARRAY['黑加仑 Blackcurrant','梨 Pear','佛手柑 Bergamot'],
 ARRAY['鸢尾 Iris','茉莉 Jasmine','橙花 Orange Blossom'],
 ARRAY['广藿香 Patchouli','零陵香豆 Tonka Bean','香草 Vanilla'],
 ARRAY['joy','romance','nostalgia'],
 ARRAY['gift','date'],
 'The beauty of life. Sweet blackcurrant and pear meet iris and orange blossom, wrapped in vanilla and patchouli. Pure happiness in a bottle.'),
('Sauvage Dior',
 ARRAY['佛手柑 Bergamot','粉红胡椒 Pink Pepper','四川花椒 Sichuan Pepper'],
 ARRAY['薰衣草 Lavender','天竺葵 Geranium','广藿香 Patchouli'],
 ARRAY['雪松 Cedar','琥珀 Ambroxan','麝香 Musk'],
 ARRAY['excitement','calm','anxiety'],
 ARRAY['work','party'],
 'Wild and fresh. Spicy bergamot and pepper burst open, lavender and geranium calm the storm, ambroxan and cedar leave a lasting mark.')
ON CONFLICT (name) DO NOTHING;
